name: relaxio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  dartz: ^0.10.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  pretty_dio_logger: ^1.4.0
  lottie: ^3.1.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  rename: ^3.1.0
  fluttertoast: ^8.2.4
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/Swimming.json

flutter_intl:
  enabled: true
